cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    # path('cart/', views.view_cart, name='view_cart'),
    path('add/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('LoaiSP', views.list_LoaiSP, name='LoaiSP'),
    path('Them_LoaiSP', views.Them_LoaiSP, name='Them_LoaiSP'),
    path('Xoa_LoaiSP/<int:loai_id>/', views.Xoa_LoaiSP, name='Xoa_LoaiSP'),
    path('Sua_LoaiSP/<int:loai_id>/', views.Sua_LoaiSP, name='Sua_LoaiSP'),

    path('NhaCungCap', views.list_NhaCungCap, name='NhaCungCap'),
    path('Them_NCC', views.Them_NCC, name='Them_NCC'),
    path('Xoa_NCC/<int:ncc_id>/', views.Xoa_NCC, name='Xoa_NCC'),
    path('Sua_NCC/<int:ncc_id>/', views.Sua_NCC, name='Sua_NCC'),

    path('SanPham', views.list_SanPham, name='SanPham'),
    path('Them_SanPham', views.Them_SanPham, name='Them_SanPham'),
    path('Xoa_SP/<int:sp_id>/', views.Xoa_SP, name='Xoa_SP'),
    path('Sua_SP/<int:sp_id>/', views.Sua_SP, name='Sua_SP'),
    path('XemCT_SP/<int:sp_id>/', views.XemCT_SP, name='Xem_SP'),
    
    path('HoaDon', views.list_HoaDon, name='HoaDon'),
    path('XemCT_HD/<int:MaHD>/', views.receiptdetails, name='Xem_HoaDon'),
    path('Huy/<int:MaHD>/', views.cancelOrder, name='Huy_HoaDon'),
    path('XacNhan/<int:MaHD>/', views.ConfirmOrder, name='XacNhan_HoaDon'),


    path('Phieu_Nhap', views.list_PhieuNhap, name='Phieu_Nhap'),
    path('LapPhieuNhap', views.LapPhieuNhap, name='LapPhieuNhap'),
    path('XemCTPN/<int:MaPhieuNhap>/', views.XemCTPN, name='Xem_PhieuNhap'),
    path('Xoa_PN/<int:id>/', views.Xoa_PN, name='Xoa_PN'),
    
    
    path('NhanVien', views.list_NhanVien, name='NhanVien'),
    path('KhachHang', views.list_KhachHang, name='KhachHang'),
]

home/urls.py
from django.urls import path
from . import views # call to url_shortener/views.py

urlpatterns = [
    path('', views.index, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
]

phoneaccessorieswebsite_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('user/', include('user.urls')),
    path('products/', include('products.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
]

dashboard/models.py
from django.db import models
from account.models import NhanVien
from products.models import SanPham, NhaCungCap

# Create your models here.

class PhieuNhap(models.Model):
    MaNV = models.ForeignKey(NhanVien, on_delete=models.CASCADE)
    NgayNhap = models.DateField()
    TrangThai = models.CharField(max_length=100)
    TongTien = models.IntegerField()
    
    def save(self, *args, **kwargs):
        if self.pk:
            self.TongTien = sum(
                chi_tiet.SoLuong * chi_tiet.GiaNhap
                for chi_tiet in self.chitietphieunhap_set.all()
            )
        super().save(*args, **kwargs)
    

class ChiTietPhieuNhap(models.Model):
    MaCTPN = models.AutoField(primary_key=True)
    MaPhieuNhap = models.ForeignKey(PhieuNhap, on_delete=models.CASCADE)
    MaSP = models.ForeignKey(SanPham, on_delete=models.CASCADE)
    MaNCC = models.ForeignKey(NhaCungCap, on_delete=models.CASCADE)
    SoLuong = models.IntegerField()
    GiaNhap = models.IntegerField()

home/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from account.models import NhanVien
from products.models import NhaCungCap,LoaiSP,SanPham
from .models import PhieuNhap, ChiTietPhieuNhap
from django.forms import inlineformset_factory

#Them Loai
class TheLoaiForm(forms.ModelForm):
    class Meta:
        model = LoaiSP
        fields = ['TenLoai']
        widgets = {
            'TenLoai': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_TenLoai(self):
        TenLoai = self.cleaned_data['TenLoai']

        try:
            LoaiSP.objects.get(TenLoai=TenLoai)
        except LoaiSP.DoesNotExist:
            return TenLoai
        raise forms.ValidationError("Loại sản phẩm đã tồn tại")

#Them NCC
class NhaCungCapForm(forms.ModelForm):
    class Meta:
        model = NhaCungCap
        fields = '__all__'
        widgets = {
            'TenNCC': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_TenNCC(self):
        TenNCC = self.cleaned_data['TenNCC']

        try:
            NhaCungCap.objects.get(TenNCC=TenNCC)
            raise forms.ValidationError("Tên nhà cung cấp đã tồn tại.")
        except NhaCungCap.DoesNotExist:
            return TenNCC


            
        
class ThemSanPhamForm(forms.ModelForm):
    class Meta:
        model = SanPham
        fields = ['TenSP', 'MaLoai', 'MaNCC', 'Mota', 'Anh', 'TenThietBi']

            
        
class SuaSanPhamForm(forms.ModelForm):
    class Meta:
        model = SanPham
        fields = ['TenSP', 'MaLoai', 'MaNCC', 'Mota', 'Anh', 'TenThietBi','Soluong','GiaNhap','GiaBan']      
    
       
        
        
# Lap Phieu Nhap Hang
class PhieuNhapForm(forms.ModelForm):
    NgayNhap = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-input','type': 'date'}))
    TrangThai = forms.BooleanField(required=True) 
    class Meta:
        model = PhieuNhap
        fields = ['MaNV', 'NgayNhap', 'TongTien','TrangThai']
        
    def __init__(self, *args, **kwargs):
        super(PhieuNhapForm, self).__init__(*args, **kwargs)
        self.fields['TongTien'].widget.attrs['readonly'] = True

class ChiTietPhieuNhapForm(forms.ModelForm):
    class Meta:
        model = ChiTietPhieuNhap
        fields = ['MaSP', 'MaNCC', 'SoLuong', 'GiaNhap']


ChiTietPhieuNhapFormSet = inlineformset_factory(
    PhieuNhap, ChiTietPhieuNhap, form=ChiTietPhieuNhapForm, extra=1, can_delete=True
)

dashboard/views.py
from pyexpat.errors import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from account.models import ChiTietHD, HoaDon, KhachHang, NhanVien
from dashboard.forms import ChiTietPhieuNhapForm, ChiTietPhieuNhapFormSet, PhieuNhapForm, SuaSanPhamForm, TheLoaiForm, NhaCungCapForm, ThemSanPhamForm
from dashboard.models import PhieuNhap,ChiTietPhieuNhap
from products.models import NhaCungCap, LoaiSP, SanPham
from django.forms.models import inlineformset_factory



def index(request):
    return render(request, 'page/dashboard.html') 

#Loại Sản Phẩm
def list_LoaiSP(request):
   data = {
   'DM_LoaiSP': LoaiSP.objects.all(), 
   }
   return render(request, 'page/LoaiSP.html', data)

def Them_LoaiSP(request):
   form = TheLoaiForm()
   if request.method == 'POST':
      form = TheLoaiForm(request.POST)
      if form.is_valid():
         form.save()
         return HttpResponseRedirect('/dashboard/LoaiSP')
   return render(request,'page/Them_LoaiSP.html',{'form':form})

def Xoa_LoaiSP(request, loai_id):
    loai_sp = LoaiSP.objects.get(id=loai_id)
    loai_sp.delete() 
    return HttpResponseRedirect('/dashboard/LoaiSP')  

def Sua_LoaiSP(request, loai_id):
    loai_sp = LoaiSP.objects.get(id=loai_id)
    if request.method == 'POST':
        form = TheLoaiForm(request.POST, instance=loai_sp)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/dashboard/LoaiSP')
    else:
        form = TheLoaiForm(instance=loai_sp)

    return render(request, 'page/Sua_LoaiSP.html', {'form': form, 'loai_sp': loai_sp})


#Nhà Cung Cấp
def list_NhaCungCap(request):
   data = {
   'DM_NCC': NhaCungCap.objects.all(), 
   }
   return render(request, 'page/NhaCungCap.html', data)


def Them_NCC(request):
    if request.method == 'POST':
        form = NhaCungCapForm(request.POST)
        if form.is_valid():
            form.save()  
            return HttpResponseRedirect('/dashboard/NhaCungCap')  
    else:
        form = NhaCungCapForm()

    context = {'form': form}
    return render(request, 'page/Them_NCC.html', context)


def Xoa_NCC(request, ncc_id):
    loai_NCC = NhaCungCap.objects.get(id=ncc_id)
    loai_NCC.delete() 
    return HttpResponseRedirect('/dashboard/NhaCungCap') 


def Sua_NCC(request, ncc_id):
    ncc = NhaCungCap.objects.get(id=ncc_id)
    if request.method == 'POST':
        form = NhaCungCapForm(request.POST, instance=ncc)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/dashboard/NhaCungCap')
    else:
        form = NhaCungCapForm(instance=ncc)

    return render(request, 'page/Sua_NCC.html', {'form': form, 'ncc': ncc})


#Sản Phẩm
def list_SanPham(request):
   data = {
   'DM_SP': SanPham.objects.all(), 
   }
   return render(request, 'page/SanPham.html', data)

def Them_SanPham(request):
    if request.method == 'POST':
        form = ThemSanPhamForm(request.POST)
        if form.is_valid():
            san_pham = form.save(commit=False)
            san_pham.Soluong = 0  
            san_pham.GiaNhap = 0
            san_pham.TrangThai =False
            san_pham.GiaBan = 0
            san_pham.save()
            return HttpResponseRedirect('/dashboard/SanPham')  
           
    else:
        form = ThemSanPhamForm()

    context = {'form': form}
    return render(request, 'page/Them_SanPham.html', context)



def Xoa_SP(request, sp_id):
    sanpham = SanPham.objects.get(id=sp_id)
    sanpham.delete()
    return HttpResponseRedirect('/dashboard/SanPham')

def Sua_SP(request, sp_id):
    sanpham = SanPham.objects.get(id=sp_id)
    if request.method == 'POST':
        form = SuaSanPhamForm(request.POST, instance=sanpham)
        if form.is_valid():
            
            form.save()
            return HttpResponseRedirect('/dashboard/SanPham')
    else:
        form = SuaSanPhamForm(instance=sanpham)

    return render(request, 'page/Sua_SP.html', {'form': form, 'sanpham': sanpham})

def XemCT_SP(request, sp_id):
    sp = SanPham.objects.get(id=sp_id)
    data = {
        'single_product': sp,
    }
    return render(request, 'page/XemCT_SP.html', data)

#HoaDon
def list_HoaDon(request):
    # invoices = HoaDon.objects.filter(MaKH=khachHang)
    chiTietHD = ChiTietHD.objects.all()
    invoices = HoaDon.objects.all()
    data = {
        'hoaDonLST': invoices,
        'chiTietHD': chiTietHD,
    }
    return render(request, 'page/HoaDon.html', data)



def receiptdetails(request, MaHD):
    # username = request.session['username']
    # khachHang = KhachHang.objects.get(UserName=username)
    hoaDon = HoaDon.objects.filter(MaHD=MaHD).first()
    chiTietHD = ChiTietHD.objects.filter(MaHD=hoaDon)
    data = {
        'hoaDon' : hoaDon,
        'chiTietHD' : chiTietHD,
    }
    return render(request, 'page/XemCT_HD.html', data)


def cancelOrder(request, MaHD):
    hoaDon = HoaDon.objects.filter(MaHD=MaHD).first()
    hoaDon.TrangThai='cancel'
    hoaDon.save()
    return redirect('HoaDon')




def ConfirmOrder(request, MaHD):
    hoaDon = HoaDon.objects.filter(MaHD=MaHD).first()
    hoaDon.TrangThai='processing'
    hoaDon.save()
    return redirect('HoaDon')


#Phiếu nhập
def list_PhieuNhap(request):
    data = {
        'DM_PhieuNhap': PhieuNhap.objects.all(),
    }
    return render(request, 'page/Phieu_Nhap.html', data)


def LapPhieuNhap(request):
    if request.method == 'POST':
        phieunhap_form = PhieuNhapForm(request.POST)
        formset = ChiTietPhieuNhapFormSet(request.POST, instance=phieunhap_form.instance)
        
        if phieunhap_form.is_valid() and formset.is_valid():
            phieunhap = phieunhap_form.save(commit=False)
            total_amount = 0
            phieunhap.save()  

            for form in formset:
                if form.cleaned_data:
                    quantity = form.cleaned_data.get('SoLuong', 0)
                    price = form.cleaned_data.get('GiaNhap', 0)
                    san_pham = form.cleaned_data.get('MaSP')
                    if san_pham:
                        san_pham.Soluong += quantity
                        san_pham.GiaNhap = price 
                        san_pham.TrangThai =True
                        san_pham.save()

                    total_amount += quantity * price
            
            phieunhap.TongTien = total_amount
            phieunhap.save()  
            formset.instance = phieunhap
            formset.save()
            
            return HttpResponseRedirect('/dashboard/Phieu_Nhap')
    else:
        phieunhap_form = PhieuNhapForm()
        formset = ChiTietPhieuNhapFormSet(instance=PhieuNhap())

    return render(request, 'page/LapPhieuNhap.html', {
        'phieunhap_form': phieunhap_form,
        'formset': formset,
    })

#xem chi tiết phiếu nhập 
def XemCTPN(request, MaPhieuNhap):
    pn = ChiTietPhieuNhap.objects.filter( MaPhieuNhap=MaPhieuNhap)
    data = {
        'DM_XemCTPN': pn,
    }
    return render(request, 'page/XemCTPN.html', data)

#xóa phiếu nhập
def Xoa_PN(request, id):
    pn = PhieuNhap.objects.get(id=id)
    pn.delete()
    return HttpResponseRedirect('/dashboard/Phieu_Nhap')

    
    
#Nhan Vien
def list_NhanVien(request):
    data = {
        'DM_NhanVien': NhanVien.objects.all(),
    }
    return render(request, 'page/NhanVien.html', data)

#KhachHang
def list_KhachHang(request):
    data = {
        'DM_KhachHang': KhachHang.objects.all(),
    }
    return render(request, 'page/KhachHang.html', data)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

from products.models import LoaiSP, SanPham
#Create your views here.
def index(request):
    data = {
        'DanhSachLoai' : LoaiSP.objects.all(),
        'DanhSachSanPham' : SanPham.objects.all(),
    }
    return render(request, 'page/home.html', data)

def aboutus(request):
    return render(request, 'page/aboutUs.html')

def contact(request):
    return render(request, 'page/contact.html')

dashboard/templates/page/KhachHang.html
{% extends "pages/layout.html" %} {% block title %} Danh Sách Khách Hàng {% endblock %} {%block libraryCSS %} {% endblock %} {%block content %}
<div class="col-9 my-3">
	<h2>
		Danh Sách Khách Hàng
	</h2>
	<table class="table my-3">
		<thead>
			<tr>
				<th scope="col">Mã KH</th>
				<th scope="col">Tên KH</th>
				<th scope="col">Giới tính</th>
				<th scope="col">Ngày Sinh</th>
				<th scope="col"></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for item in DM_KhachHang %}
			<tr>
				<td>{{ item.MaKH }}</td>
				<td>{{ item.TenKH }}</td>
				<td>{{ item.GioiTinh }}</td>
				<td>{{ item.NgaySinh }}</td>
				<td>
					<a href="#">Xem chi tiết</a>
					<a href="#" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này?')">Xóa</a>
					<a href="#">Sửa</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

dashboard/templates/page/LapPhieuNhap.html
{% extends "pages/layout.html" %}
{% block title %}Lập Phiếu Nhập{% endblock %}
{% block content %}
<div class="col-9 my-3" >
    <form method="post" action="/dashboard/LapPhieuNhap">
        {% csrf_token %}
        <center><h2>Lập Phiếu Nhập</h2></center>
        <br><br>
        {{ phieunhap_form.as_table }}
        <br><br><br>
        {{ formset.management_form }}
        <div id="formset">
            {% for form in formset %}
                <div class="form-row">
                    {{ form.as_table }}
                </div>
            {% endfor %}
        </div>
        <br>
        <h3>Tổng Tiền: <span id="total-amount">0</span></h3>
        <input type="hidden" id="id_TongTien" name="TongTien" value="0">

        <button type="submit" style="margin-left: 500px;">Save</button>
    </form>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const formset = document.getElementById('formset');
    const totalAmountElement = document.getElementById('total-amount');
    const totalAmountInput = document.getElementById('id_TongTien');
    
    function calculateTotal() {
        let totalAmount = 0;
        const rows = formset.querySelectorAll('.form-row');
        rows.forEach(row => {
            const quantityInput = row.querySelector('input[name$="-SoLuong"]');
            const priceInput = row.querySelector('input[name$="-GiaNhap"]');
            const quantity = parseInt(quantityInput.value) || 0;
            const price = parseInt(priceInput.value) || 0;
            totalAmount += quantity * price;
        });
        totalAmountElement.textContent = totalAmount;
        totalAmountInput.value = totalAmount;
    }

    formset.addEventListener('input', function(event) {
        if (event.target.name.endsWith('-SoLuong') || event.target.name.endsWith('-GiaNhap')) {
            calculateTotal();
        }
    });

    calculateTotal();
});
</script>

{% endblock %}

dashboard/templates/page/NhaCungCap.html
{% extends "pages/layout.html" %} {% block title %} Thể Loại {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" >
    <h2>Danh Sách Nhà Cung Cấp <a href="{% url 'Them_NCC' %}" class="btn btn-primary" style="margin-left: 300px;">Thêm Nhà Cung Cấp</a></h2>
    <table class="table my-3">
        <thead>
          <tr>
            <th scope="col">Nhà Cung Cấp</th>
            <th scope="col">Địa Chỉ</th>
            <th scope="col">Email</th>
            <th scope="col">SDT</th>
            <th scope="col">Website</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for item in DM_NCC %}
          <tr>
            <td>{{ item.TenNCC }}</td>
            <td>{{ item.DiaChi }}</td>
            <td>{{ item.Email }}</td>
            <td>{{ item.SDT }}</td>
            <td>{{ item.WebSite }}</td>
            <td><a href="/dashboard/Xoa_NCC/{{item.id}}" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này?')">Xóa</a>
            <a href="/dashboard/Sua_NCC/{{item.id}}">Sửa</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
</div>
{% endblock %}

dashboard/templates/page/NhanVien.html
{% extends "pages/layout.html" %} {% block title %} Thể Loại {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" >
    <h2>Danh Sách Nhân Viên <a href="#" class="btn btn-primary" style="margin-left: 300px;">Thêm Nhân Viên</a></h2>
    <table class="table my-3">
        <thead>
          <tr>
            <th scope="col">Mã nhân viên</th>
            <th scope="col">Tên nhân viên</th>
            <th scope="col">Giới tính</th>
            <th scope="col">Ngày Sinh</th>
            <th scope="col"></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for item in DM_NhanVien %}
          <tr>
            <td>{{ item.MaNV }}</td>
            <td>{{ item.TenNV }}</td>
            <td>{{ item.GioiTinh }}</td>
            <td>{{ item.NgaySinh }}</td>
            <td>
            <a href="#">Xem chi tiết</a>
            <a href="#" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này?')">Xóa</a>
            <a href="#">Sửa</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
</div>
{% endblock %}

dashboard/templates/page/Phieu_Nhap.html
{% extends "pages/layout.html" %} {% block title %} Thể Loại {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" >
    <h2>Danh Sách Phiếu Nhập<a href="{% url 'LapPhieuNhap' %}" class="btn btn-primary" style="margin-left: 300px;">Thêm phiếu nhập</a></h2>
    <table class="table my-3">
        <thead>
          <tr>
            <th>Mã Nhân Viên</th>
            <th>Ngày Nhập</th>
            <th>Trạng Thái</th>
            <th>Tổng Tiền</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in DM_PhieuNhap %}
            <tr>
            <td>{{ item.MaNV }}</td>
            <td>{{ item.NgayNhap }}</td>
            <td>{{ item.TrangThai }}</td>
            <td>{{ item.TongTien }}</td>
            <td>
                <a href="/dashboard/XemCTPN/{{item.id}}">Xem chi tiết</a>
                <a href="/dashboard/Xoa_PN/{{item.id}}" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này?')">Xóa</a>
                <a href="#">Sửa</a>
            </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% endblock %}

dashboard/templates/page/SanPham.html
{% extends "pages/layout.html" %} {% block title %} Thể Loại {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" >
    <h2>Danh Sách Sản Phẩm<a href="{% url 'Them_SanPham' %}" class="btn btn-primary" style="margin-left: 300px;">Thêm Sản Phẩm</a></h2>
    <table class="table my-3">
        <thead>
          <tr>
            <th>Hình ảnh</th>
            <th>Tên Sản phẩm</th>
            <th>Số lượng</th>
            <th>Giá bán</th>
            <th>Giá nhập</th>
            <th>Trạng thái</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in DM_SP %}
            <tr>
            <td><img src="/static/img/{{ item.Anh }}" width="100" ></td>
            <td>{{ item.TenSP }}</td>
            <td>{{ item.Soluong }}</td>
            <td>{{ item.GiaBan }}</td>
            <td>{{ item.GiaNhap }}</td>
            <td>{{ item.TrangThai }}</td>
            <td>
                <a href="/dashboard/XemCT_SP/{{item.id}}">Xem chi tiết</a>
                <a href="/dashboard/Xoa_SP/{{item.id}}" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm này?')">Xóa</a>
                <a href="/dashboard/Sua_SP/{{item.id}}">Sửa</a>
            </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
</div>
{% endblock %}

dashboard/templates/page/Sua_SP.html
{% extends "pages/layout.html" %} {% block title %} Dashboard {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" > 
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Lưu</button>
    </form>
</div>
{% endblock %}

dashboard/templates/page/Them_LoaiSP.html
{% extends "pages/layout.html" %} {% block title %} Thêm Thể loại {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" > 
    <form action="/dashboard/Them_LoaiSP" method="post">
        {% csrf_token %}
        <h2>Thêm Thể Loại</h2>
        {{ form.as_ul }}
        <input type="submit" value="Thêm">
      </form>
</div>
{% endblock %}

dashboard/templates/page/Them_NCC.html
{% extends "pages/layout.html" %} {% block title %} Dashboard {% endblock %} {%block libraryCSS %}
{% endblock %} {%block content %}
<div class="col-9 my-3" > 
    <form action="/dashboard/Them_NCC" method="post">
        {% csrf_token %}
        <h2>Thêm nhà cung cấp</h2>
        {{ form.as_p }}
        <input type="submit" value="Thêm">
      </form>
</div>
{% endblock %}

dashboard/templates/page/XemCTPN.html
{% extends "pages/layout.html" %}
{% block title %} Xem Chi Tiết Sản Phẩm {% endblock %}
{% block libraryCSS %}

{% endblock %}
{% block content %}
<div class="col-9 my-3">
    {% for item in DM_XemCTPN %}
    <p>MaCTPN: {{ item.MaCTPN }}</p>
    <p>MaPhieuNhap: {{ item.MaPhieuNhap }}</p>
    <p> MaSP: {{ item.MaSP }}</p>
    <p>MaNCC: {{ item.MaNCC }}</p>
    <p>SoLuong: {{ item.SoLuong }}</p>
    <p> GiaNhap: {{ item.GiaNhap }}</p>
{% endfor %}
   
</div>
{% endblock %}
    

dashboard/templates/page/XemCT_SP.html
{% extends "pages/layout.html" %}
{% block title %} Xem Chi Tiết Sản Phẩm {% endblock %}
{% block libraryCSS %}

{% endblock %}
{% block content %}
<div class="col-9 my-3">
    <h1>Chi Tiết Sản Phẩm</h1>
    <p>Tên sản phẩm: {{ single_product.TenSP }}</p>
    <p>Số lượng: {{ single_product.Soluong }}</p>
    <p>Giá nhập: {{ single_product.GiaNhap }}</p>
    <p>Giá bán: {{ single_product.GiaBan }}</p>
    <p>Mã Loại: {{ single_product.MaLoai }}</p>
    <p>Mã Nhà Cung Cấp: {{ single_product.MaNCC }}</p>
    <p>Mô tả: {{ single_product.Mota }}</p>
    <p>Trạng thái: {% if single_product.TrangThai %}Có hàng{% else %}Không có hàng{% endif %}</p>
    <div class="img-big-wrag"> 
        <p>Hình ảnh :
        <img class="w-100" src="/static/img/{{ single_product.Anh }}"/></p>
    </div>
    <p>Tên Thiết Bị: {{ single_product.TenThietBi }}</p>
</div>
{% endblock %}

dashboard/templates/page/dashboard.html
{% extends "pages/layout.html" %} {% block title %} Dashboard {% endblock %} {%block libraryCSS %}
<style>
	.nav-category .nav-item .nav-link {
		align-items: center;
		color: #001e2b;
		display: flex;
		justify-content: space-between;
		padding: 8px 0;
	}
</style>
{% endblock %} {%block content %} {% endblock %}